//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewShop_TAM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<v_Promo_Statement_Inv> v_Promo_Statement_Inv { get; set; }
        public virtual DbSet<v_SupSlm_Customer> v_SupSlm_Customer { get; set; }
        public virtual DbSet<v_Promo_Statement_Customer> v_Promo_Statement_Customer { get; set; }
        public virtual DbSet<v_Promo_Statement_Reward> v_Promo_Statement_Reward { get; set; }
    }
}
