//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewShop_TAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Promo_Statement_Customer
    {
        public string CUSCOD { get; set; }
        public string CUSNAM { get; set; }
        public string SLMNAM { get; set; }
        public string SLMCOD { get; set; }
        public string ADDR_01 { get; set; }
        public string add1 { get; set; }
        public string add2 { get; set; }
        public string TELNUM { get; set; }
        public System.DateTime Asof { get; set; }
        public string CUSKEY { get; set; }
    }
}
