//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewShop_TAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Promo_Statement_Inv
    {
        public string COMP { get; set; }
        public string CUSKEY { get; set; }
        public string StYr { get; set; }
        public Nullable<decimal> LastTotal { get; set; }
        public Nullable<decimal> LastPayTotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Jan { get; set; }
        public Nullable<decimal> Feb { get; set; }
        public Nullable<decimal> Mar { get; set; }
        public Nullable<decimal> Apr { get; set; }
        public Nullable<decimal> May { get; set; }
        public Nullable<decimal> Jun { get; set; }
        public Nullable<decimal> Jul { get; set; }
        public Nullable<decimal> Aug { get; set; }
        public Nullable<decimal> Sep { get; set; }
        public Nullable<decimal> Oct { get; set; }
        public Nullable<decimal> Nov { get; set; }
        public Nullable<decimal> Dec { get; set; }
        public Nullable<decimal> PayTotal { get; set; }
        public Nullable<decimal> PayJan { get; set; }
        public Nullable<decimal> PayFeb { get; set; }
        public Nullable<decimal> PayMar { get; set; }
        public Nullable<decimal> PayApr { get; set; }
        public Nullable<decimal> PayMay { get; set; }
        public Nullable<decimal> PayJun { get; set; }
        public Nullable<decimal> PayJul { get; set; }
        public Nullable<decimal> PayAug { get; set; }
        public Nullable<decimal> PaySep { get; set; }
        public Nullable<decimal> PayOct { get; set; }
        public Nullable<decimal> PayNov { get; set; }
        public Nullable<decimal> PayDec { get; set; }
        public Nullable<System.DateTime> Asof { get; set; }
    }
}
