//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewShopTAM_TAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Promo_Statement_Reward
    {
        public string PYear { get; set; }
        public string CUSCOD { get; set; }
        public string CusNam { get; set; }
        public string SLMCOD { get; set; }
        public string Promotion_Code { get; set; }
        public string Promotion_Name { get; set; }
        public Nullable<double> SAMT { get; set; }
        public Nullable<double> SPaidAMT { get; set; }
        public int Condition { get; set; }
        public string Reward { get; set; }
        public Nullable<int> PrnFlg { get; set; }
        public Nullable<int> CalTyp { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal reward_amt { get; set; }
    }
}
