//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewShopTAM_TAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SupSlm_Customer
    {
        public string SUP { get; set; }
        public string CUSNAM { get; set; }
        public string SLMCOD { get; set; }
        public string CUSCOD { get; set; }
    }
}
